base_url: "http://localhost:8080"

mysql:
  host: "47.110.90.47"
  port: 3306
  user: "root1"
  password: "QAZwsx123."
  database: "l_table"

login:
  url: "/api/login"
  phone: "15377095676"
  password: "hjj123456."
